# Generated by Django 5.2.16 on 2026-07-10 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raqam",
                    models.CharField(
                        help_text="Masalan: 1.01 yoki 2.03", max_length=10
                    ),
                ),
                (
                    "turi",
                    models.CharField(
                        choices=[("MAJBURIY", "Majburiy"), ("TANLOV", "Tanlov")],
                        max_length=10,
                    ),
                ),
                ("jami_soat", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Fan",
                "verbose_name_plural": "Fanlar",
                "ordering": ["raqam"],
            },
        ),
        migrations.CreateModel(
            name="FanVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kodi", models.CharField(blank=True, max_length=50)),
                ("nomi", models.CharField(max_length=255)),
                ("auditoriya_soat", models.PositiveIntegerField(default=0)),
                ("maruza_soat", models.PositiveIntegerField(default=0)),
                ("amaliyot_soat", models.PositiveIntegerField(default=0)),
                ("laboratoriya_soat", models.PositiveIntegerField(default=0)),
                ("seminar_soat", models.PositiveIntegerField(default=0)),
                ("kurs_ishi_soat", models.PositiveIntegerField(default=0)),
                (
                    "fan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variantlar",
                        to="plans.fan",
                    ),
                ),
                (
                    "kafedra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fanlar",
                        to="accounts.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fan varianti",
                "verbose_name_plural": "Fan variantlari",
            },
        ),
        migrations.CreateModel(
            name="FanSemestr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semestr", models.PositiveSmallIntegerField()),
                ("kredit", models.PositiveSmallIntegerField(default=0)),
                ("haftalik_soat", models.PositiveSmallIntegerField(default=0)),
                ("maruza_soat", models.PositiveIntegerField(default=0)),
                ("amaliyot_soat", models.PositiveIntegerField(default=0)),
                ("laboratoriya_soat", models.PositiveIntegerField(default=0)),
                ("seminar_soat", models.PositiveIntegerField(default=0)),
                ("kurs_ishi_bor", models.BooleanField(default=False)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semestrlar",
                        to="plans.fanvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fan semestri",
                "verbose_name_plural": "Fan semestrlari",
                "ordering": ["semestr"],
            },
        ),
        migrations.AddField(
            model_name="fan",
            name="tanlangan_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="plans.fanvariant",
            ),
        ),
        migrations.CreateModel(
            name="OquvReja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yonalish_kodi", models.CharField(max_length=20)),
                ("yonalish_nomi", models.CharField(max_length=255)),
                ("boshlanish_yili", models.PositiveSmallIntegerField()),
                ("daraja", models.CharField(blank=True, max_length=100)),
                ("talim_shakli", models.CharField(blank=True, max_length=100)),
                ("davomiylik_yil", models.PositiveSmallIntegerField(default=4)),
                ("talabalar_soni", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "guruhlar_soni",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "guruh_prefiksi",
                    models.CharField(
                        blank=True, default="", help_text="Masalan: DI", max_length=20
                    ),
                ),
                ("manba_fayl", models.CharField(blank=True, max_length=255)),
                ("import_vaqti", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "O'quv reja",
                "verbose_name_plural": "O'quv rejalar",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("yonalish_kodi", "boshlanish_yili", "talim_shakli"),
                        name="uniq_reja_kod_yil_shakl",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Guruh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raqam", models.PositiveSmallIntegerField()),
                ("nomi", models.CharField(max_length=50)),
                (
                    "reja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guruhlar",
                        to="plans.oquvreja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guruh",
                "verbose_name_plural": "Guruhlar",
                "ordering": ["reja", "raqam"],
            },
        ),
        migrations.AddField(
            model_name="fan",
            name="reja",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fanlar",
                to="plans.oquvreja",
            ),
        ),
        migrations.CreateModel(
            name="Yuklama",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tur",
                    models.CharField(
                        choices=[
                            ("MARUZA", "Ma'ruza"),
                            ("AMALIYOT", "Amaliyot"),
                            ("LABORATORIYA", "Laboratoriya"),
                            ("SEMINAR", "Seminar"),
                            ("KURS_ISHI", "Kurs ishi"),
                        ],
                        max_length=15,
                    ),
                ),
                ("talabalar_soni", models.PositiveIntegerField(blank=True, null=True)),
                ("soat", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "fan_semestr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="yuklamalar",
                        to="plans.fansemestr",
                    ),
                ),
                (
                    "guruh",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="yuklamalar",
                        to="plans.guruh",
                    ),
                ),
                (
                    "oqituvchi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="yuklamalar",
                        to="accounts.oqituvchiprofil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yuklama",
                "verbose_name_plural": "Yuklamalar",
            },
        ),
        migrations.AddConstraint(
            model_name="fanvariant",
            constraint=models.UniqueConstraint(
                fields=("fan", "kodi", "nomi"), name="uniq_variant_fan_kod_nom"
            ),
        ),
        migrations.AddConstraint(
            model_name="fansemestr",
            constraint=models.UniqueConstraint(
                fields=("variant", "semestr"), name="uniq_fansemestr"
            ),
        ),
        migrations.AddConstraint(
            model_name="fansemestr",
            constraint=models.CheckConstraint(
                condition=models.Q(("semestr__gte", 1), ("semestr__lte", 12)),
                name="chk_semestr_oraliq",
            ),
        ),
        migrations.AddConstraint(
            model_name="guruh",
            constraint=models.UniqueConstraint(
                fields=("reja", "raqam"), name="uniq_guruh_raqam"
            ),
        ),
        migrations.AddConstraint(
            model_name="guruh",
            constraint=models.UniqueConstraint(
                fields=("reja", "nomi"), name="uniq_guruh_nomi"
            ),
        ),
        migrations.AddIndex(
            model_name="fan",
            index=models.Index(
                fields=["reja", "turi"], name="plans_fan_reja_id_802b7c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fan",
            constraint=models.UniqueConstraint(
                fields=("reja", "raqam"), name="uniq_fan_raqam"
            ),
        ),
        migrations.AddIndex(
            model_name="yuklama",
            index=models.Index(
                fields=["oqituvchi", "tur"], name="plans_yukla_oqituvc_dd0bef_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="yuklama",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tur", "MARUZA")),
                fields=("fan_semestr", "tur"),
                name="uniq_maruza_yuklama",
            ),
        ),
        migrations.AddConstraint(
            model_name="yuklama",
            constraint=models.UniqueConstraint(
                condition=models.Q(("guruh__isnull", False)),
                fields=("fan_semestr", "tur", "guruh"),
                name="uniq_guruh_yuklama",
            ),
        ),
        migrations.AddConstraint(
            model_name="yuklama",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tur", "KURS_ISHI")),
                fields=("fan_semestr", "tur", "oqituvchi"),
                name="uniq_kursishi_oqituvchi",
            ),
        ),
        migrations.AddConstraint(
            model_name="yuklama",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("guruh__isnull", False),
                        ("talabalar_soni__isnull", True),
                        ("tur__in", ["AMALIYOT", "LABORATORIYA", "SEMINAR"]),
                    ),
                    models.Q(
                        ("guruh__isnull", True),
                        ("talabalar_soni__isnull", True),
                        ("tur", "MARUZA"),
                    ),
                    models.Q(
                        ("guruh__isnull", True),
                        ("talabalar_soni__gt", 0),
                        ("talabalar_soni__isnull", False),
                        ("tur", "KURS_ISHI"),
                    ),
                    _connector="OR",
                ),
                name="chk_yuklama_shakl",
            ),
        ),
    ]
