# Generated by Django 5.2.16 on 2026-08-15 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BilimSohasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kodi", models.CharField(max_length=10, unique=True)),
                ("nomi", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Bilim sohasi",
                "verbose_name_plural": "Bilim sohalari",
                "ordering": ["kodi"],
            },
        ),
        migrations.AlterField(
            model_name="oquvreja",
            name="yonalish_kodi",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="oquvreja",
            name="yonalish_nomi",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.CreateModel(
            name="TalimSohasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kodi", models.CharField(max_length=10, unique=True)),
                ("nomi", models.CharField(max_length=255)),
                (
                    "bilim_sohasi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="talim_sohalari",
                        to="plans.bilimsohasi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ta'lim sohasi",
                "verbose_name_plural": "Ta'lim sohalari",
                "ordering": ["kodi"],
            },
        ),
        migrations.CreateModel(
            name="TalimYonalishi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kodi", models.CharField(max_length=20, unique=True)),
                ("nomi", models.CharField(max_length=255)),
                (
                    "talim_sohasi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="yonalishlar",
                        to="plans.talimsohasi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ta'lim yo'nalishi",
                "verbose_name_plural": "Ta'lim yo'nalishlari",
                "ordering": ["kodi"],
            },
        ),
        migrations.AddField(
            model_name="oquvreja",
            name="talim_yonalishi",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rejalar",
                to="plans.talimyonalishi",
            ),
        ),
    ]
