# Generated by Django 5.2.16 on 2026-08-15 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0003_talim_yonalishi_backfill"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="oquvreja",
            name="uniq_reja_kod_yil_shakl",
        ),
        migrations.RemoveField(
            model_name="oquvreja",
            name="yonalish_kodi",
        ),
        migrations.RemoveField(
            model_name="oquvreja",
            name="yonalish_nomi",
        ),
        migrations.AlterField(
            model_name="oquvreja",
            name="talim_yonalishi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rejalar",
                to="plans.talimyonalishi",
            ),
        ),
        migrations.AddConstraint(
            model_name="oquvreja",
            constraint=models.UniqueConstraint(
                fields=("talim_yonalishi", "boshlanish_yili", "talim_shakli"),
                name="uniq_reja_kod_yil_shakl",
            ),
        ),
    ]
