# Generated by Django 5.2.16 on 2026-08-15 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0006_oquvreja_sohalar_backfill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oquvreja",
            name="bilim_sohasi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rejalar",
                to="plans.bilimsohasi",
            ),
        ),
        migrations.AlterField(
            model_name="oquvreja",
            name="talim_sohasi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rejalar",
                to="plans.talimsohasi",
            ),
        ),
    ]
