# Generated by Django 5.2.16 on 2026-09-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0010_drop_bilim_talim_sohasi_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="TalimYonalishi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kodi", models.CharField(max_length=20, unique=True)),
                ("nomi", models.CharField(max_length=255)),
                ("bilim_sohasi_kodi", models.CharField(max_length=10)),
                ("bilim_sohasi_nomi", models.CharField(max_length=255)),
                ("talim_sohasi_kodi", models.CharField(max_length=10)),
                ("talim_sohasi_nomi", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Ta'lim yo'nalishi (klassifikator)",
                "verbose_name_plural": "Ta'lim yo'nalishlari (klassifikator)",
                "ordering": ["kodi"],
            },
        ),
    ]
