# Generated by Django 5.2.16 on 2026-09-02 04:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_department_fakultet"),
        ("plans", "0012_talimyonalishi_klassifikator_seed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DasturTopshirish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fayl", models.FileField(upload_to="dasturlar/%Y/")),
                (
                    "holat",
                    models.CharField(
                        choices=[
                            ("KUTILMOQDA", "Ko'rib chiqilmoqda"),
                            ("QABUL_QILINDI", "Qabul qilindi"),
                            ("RAD_ETILDI", "Rad etildi"),
                        ],
                        default="KUTILMOQDA",
                        max_length=20,
                    ),
                ),
                ("izoh", models.TextField(blank=True)),
                (
                    "yuborilgan_vaqt",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("korib_chiqilgan_vaqt", models.DateTimeField(blank=True, null=True)),
                (
                    "korib_chiqqan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "oqituvchi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dastur_topshirishlari",
                        to="accounts.oqituvchiprofil",
                    ),
                ),
                (
                    "variant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dastur_topshirish",
                        to="plans.fanvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dastur topshirig'i",
                "verbose_name_plural": "Dastur topshiriqlari",
                "ordering": ["-yuborilgan_vaqt"],
            },
        ),
    ]
