# Generated by Django 5.2.16 on 2026-08-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Universitet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rasmiy_nomi", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Universitet",
                "verbose_name_plural": "Universitet",
            },
        ),
    ]
