# Generated by Django 5.2.16 on 2026-08-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_universitet"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="fakultet",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
